#!/bin/bash
# postrm - dpkg safe

rm -f /etc/dconf/db/local.d/locks/desktop-background-lock
rm -f /etc/dconf/db/local.d/desktop-background
rm -f /etc/dconf/profile/user

dconf update

rmdir --ignore-fail-on-non-empty /etc/dconf/db/local.d/locks || true
rmdir --ignore-fail-on-non-empty /etc/dconf/db/local.d || true
rmdir --ignore-fail-on-non-empty /etc/dconf/profile || true

exit 0

